# Generated by Django 4.2.18 on 2025-01-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_name_menuitem_title_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.CharField(max_length=100, verbose_name='User'),
        ),
    ]
