# Generated by Django 4.2.18 on 2025-01-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
    ]
